### PR TITLE
Buckets in Region us-east-1 have a LocationConstraint of null

### PR DESCRIPTION
**Pull request by aleksmark**
I tried to create the stack but it failed with an error: `TypeError: str expected, not NoneType`

CloudWatch log:
```...
2021-05-27T11:21:37.220+02:00	Environment variables have been set.
2021-05-27T11:21:37.220+02:00	Verifying IAM roles
2021-05-27T11:21:37.220+02:00	Verifying bucket
2021-05-27T11:21:38.409+02:00	S3 bucket is valid.
2021-05-27T11:21:38.409+02:00	x.x.x.x
2021-05-27T11:21:38.428+02:00	Traceback (most recent call last):
2021-05-27T11:21:38.428+02:00	File "/var/task/aviatrix_ha.py", line 128, in _lambda_handler
2021-05-27T11:21:38.428+02:00	response_status, err_reason = handle_cloud_formation_request(
2021-05-27T11:21:38.428+02:00	File "/var/task/aviatrix_ha.py", line 190, in handle_cloud_formation_request
2021-05-27T11:21:38.428+02:00	os.environ['S3_BUCKET_REGION'] = bucket_region
2021-05-27T11:21:38.428+02:00	File "/var/lang/lib/python3.8/os.py", line 680, in __setitem__
2021-05-27T11:21:38.428+02:00	value = self.encodevalue(value)
2021-05-27T11:21:38.428+02:00	File "/var/lang/lib/python3.8/os.py", line 750, in encode
2021-05-27T11:21:38.428+02:00	raise TypeError("str expected, not %s" % type(value).__name__)
2021-05-27T11:21:38.428+02:00	TypeError: str expected, not NoneType
2021-05-27T11:21:38.605+02:00	Status code: 200
2021-05-27T11:21:38.605+02:00	Status message: OK
2021-05-27T11:21:38.607+02:00	Sent FAILED to CFT.
```

After going through the boto3 docs, I found out that **Buckets in Region us-east-1 have a LocationConstraint of null**
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.get_bucket_location

AWS docs support the claim
https://docs.aws.amazon.com/cli/latest/reference/s3api/get-bucket-location.html#output

This PR handles the use case.

### CODE REVIEW

**Comment by arvindsree** [comment]
Thank you for the PR.

**Comment by aleksmark** [comment]
@arvindsree when will the new version be available on https://aviatrix-lambda-us-east-1.s3.amazonaws.com/aviatrix_ha.zip ?

**Comment by arvindsree** [comment]
Sorry for not responding earlier. We have pushed it out to https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=AviatrixHA&templateURL=https://aviatrix-cloudformation-templates.s3-us-west-2.amazonaws.com/aviatrix-aws-existing-controller-ha-dev.json . We will notify you when we push it to the official CFT after we have completed our validation.

**Comment by arvindsree** [comment]
Hi. The fix has been pushed to the official CFT bucket

**Comment by aleksmark** [comment]
Great, thank you.

**Pull request merged**
